/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AnswerRequest,
  HTTPValidationError,
  TopAnswersResponse,
} from '../models/index';
import {
    AnswerRequestFromJSON,
    AnswerRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    TopAnswersResponseFromJSON,
    TopAnswersResponseToJSON,
} from '../models/index';

export interface FindTopAnswersFindAnswerPostRequest {
    answerRequest: AnswerRequest;
}

/**
 * 
 */
export class AnswerRetrievalApi extends runtime.BaseAPI {

    /**
     * Accepts a text query, finds the top 3 most similar historical tickets,  and returns their answer patterns.
     * Find Top Answers
     */
    async findTopAnswersFindAnswerPostRaw(requestParameters: FindTopAnswersFindAnswerPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TopAnswersResponse>> {
        if (requestParameters['answerRequest'] == null) {
            throw new runtime.RequiredError(
                'answerRequest',
                'Required parameter "answerRequest" was null or undefined when calling findTopAnswersFindAnswerPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/find-answer`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AnswerRequestToJSON(requestParameters['answerRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TopAnswersResponseFromJSON(jsonValue));
    }

    /**
     * Accepts a text query, finds the top 3 most similar historical tickets,  and returns their answer patterns.
     * Find Top Answers
     */
    async findTopAnswersFindAnswerPost(requestParameters: FindTopAnswersFindAnswerPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TopAnswersResponse> {
        const response = await this.findTopAnswersFindAnswerPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
