/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnswerRequest
 */
export interface AnswerRequest {
    /**
     * 
     * @type {string}
     * @memberof AnswerRequest
     */
    text: string;
}

/**
 * Check if a given object implements the AnswerRequest interface.
 */
export function instanceOfAnswerRequest(value: object): value is AnswerRequest {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function AnswerRequestFromJSON(json: any): AnswerRequest {
    return AnswerRequestFromJSONTyped(json, false);
}

export function AnswerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnswerRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
    };
}

export function AnswerRequestToJSON(json: any): AnswerRequest {
    return AnswerRequestToJSONTyped(json, false);
}

export function AnswerRequestToJSONTyped(value?: AnswerRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
    };
}

