/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PredictionRequest
 */
export interface PredictionRequest {
    /**
     * 
     * @type {string}
     * @memberof PredictionRequest
     */
    text: string;
}

/**
 * Check if a given object implements the PredictionRequest interface.
 */
export function instanceOfPredictionRequest(value: object): value is PredictionRequest {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function PredictionRequestFromJSON(json: any): PredictionRequest {
    return PredictionRequestFromJSONTyped(json, false);
}

export function PredictionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PredictionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
    };
}

export function PredictionRequestToJSON(json: any): PredictionRequest {
    return PredictionRequestToJSONTyped(json, false);
}

export function PredictionRequestToJSONTyped(value?: PredictionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
    };
}

