/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PredictionResponse
 */
export interface PredictionResponse {
    /**
     * 
     * @type {string}
     * @memberof PredictionResponse
     */
    prediction: string;
    /**
     * 
     * @type {string}
     * @memberof PredictionResponse
     */
    parent: string;
    /**
     * 
     * @type {number}
     * @memberof PredictionResponse
     */
    confidence: number;
    /**
     * 
     * @type {number}
     * @memberof PredictionResponse
     */
    parentConfidence: number;
    /**
     * 
     * @type {boolean}
     * @memberof PredictionResponse
     */
    routed: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof PredictionResponse
     */
    top3: Array<string>;
}

/**
 * Check if a given object implements the PredictionResponse interface.
 */
export function instanceOfPredictionResponse(value: object): value is PredictionResponse {
    if (!('prediction' in value) || value['prediction'] === undefined) return false;
    if (!('parent' in value) || value['parent'] === undefined) return false;
    if (!('confidence' in value) || value['confidence'] === undefined) return false;
    if (!('parentConfidence' in value) || value['parentConfidence'] === undefined) return false;
    if (!('routed' in value) || value['routed'] === undefined) return false;
    if (!('top3' in value) || value['top3'] === undefined) return false;
    return true;
}

export function PredictionResponseFromJSON(json: any): PredictionResponse {
    return PredictionResponseFromJSONTyped(json, false);
}

export function PredictionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PredictionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'prediction': json['prediction'],
        'parent': json['parent'],
        'confidence': json['confidence'],
        'parentConfidence': json['parent_confidence'],
        'routed': json['routed'],
        'top3': json['top3'],
    };
}

export function PredictionResponseToJSON(json: any): PredictionResponse {
    return PredictionResponseToJSONTyped(json, false);
}

export function PredictionResponseToJSONTyped(value?: PredictionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prediction': value['prediction'],
        'parent': value['parent'],
        'confidence': value['confidence'],
        'parent_confidence': value['parentConfidence'],
        'routed': value['routed'],
        'top3': value['top3'],
    };
}

