/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RetrievedAnswerItem
 */
export interface RetrievedAnswerItem {
    /**
     * 
     * @type {string}
     * @memberof RetrievedAnswerItem
     */
    retrievedAnswer: string;
    /**
     * 
     * @type {string}
     * @memberof RetrievedAnswerItem
     */
    matchedQuery: string;
    /**
     * 
     * @type {number}
     * @memberof RetrievedAnswerItem
     */
    similarityScore: number;
}

/**
 * Check if a given object implements the RetrievedAnswerItem interface.
 */
export function instanceOfRetrievedAnswerItem(value: object): value is RetrievedAnswerItem {
    if (!('retrievedAnswer' in value) || value['retrievedAnswer'] === undefined) return false;
    if (!('matchedQuery' in value) || value['matchedQuery'] === undefined) return false;
    if (!('similarityScore' in value) || value['similarityScore'] === undefined) return false;
    return true;
}

export function RetrievedAnswerItemFromJSON(json: any): RetrievedAnswerItem {
    return RetrievedAnswerItemFromJSONTyped(json, false);
}

export function RetrievedAnswerItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetrievedAnswerItem {
    if (json == null) {
        return json;
    }
    return {
        
        'retrievedAnswer': json['retrieved_answer'],
        'matchedQuery': json['matched_query'],
        'similarityScore': json['similarity_score'],
    };
}

export function RetrievedAnswerItemToJSON(json: any): RetrievedAnswerItem {
    return RetrievedAnswerItemToJSONTyped(json, false);
}

export function RetrievedAnswerItemToJSONTyped(value?: RetrievedAnswerItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'retrieved_answer': value['retrievedAnswer'],
        'matched_query': value['matchedQuery'],
        'similarity_score': value['similarityScore'],
    };
}

