/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RetrievedAnswerItem } from './RetrievedAnswerItem';
import {
    RetrievedAnswerItemFromJSON,
    RetrievedAnswerItemFromJSONTyped,
    RetrievedAnswerItemToJSON,
    RetrievedAnswerItemToJSONTyped,
} from './RetrievedAnswerItem';

/**
 * 
 * @export
 * @interface TopAnswersResponse
 */
export interface TopAnswersResponse {
    /**
     * 
     * @type {Array<RetrievedAnswerItem>}
     * @memberof TopAnswersResponse
     */
    answers: Array<RetrievedAnswerItem>;
}

/**
 * Check if a given object implements the TopAnswersResponse interface.
 */
export function instanceOfTopAnswersResponse(value: object): value is TopAnswersResponse {
    if (!('answers' in value) || value['answers'] === undefined) return false;
    return true;
}

export function TopAnswersResponseFromJSON(json: any): TopAnswersResponse {
    return TopAnswersResponseFromJSONTyped(json, false);
}

export function TopAnswersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopAnswersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'answers': ((json['answers'] as Array<any>).map(RetrievedAnswerItemFromJSON)),
    };
}

export function TopAnswersResponseToJSON(json: any): TopAnswersResponse {
    return TopAnswersResponseToJSONTyped(json, false);
}

export function TopAnswersResponseToJSONTyped(value?: TopAnswersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'answers': ((value['answers'] as Array<any>).map(RetrievedAnswerItemToJSON)),
    };
}

